image: docker:latest

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - docker info
    - docker build -t adakimov/test-cicd .

deploy-dockerhub:
  stage: deploy
  before_script:
    - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  script:
    - docker push adakimov/test-cicd